name: Deploy with npm run deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write   # required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build
        run: npm run build

      - name: Deploy (gh-pages with token)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d build \
            -u "github-actions[bot] <github-actions[bot]@users.noreply.github.com>" \
            -r "https://x-access-token:${GITHUB_TOKEN}@github.com/SuperRitchie/chess.git"
